import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from '@react-pdf/renderer'
import { calculateQuoteTotals } from '../utils/calculations'
import { formatCurrency } from '../utils/format'

export default function QuoteDocument({ quote, premiumUnlocked }) {
  const totals = calculateQuoteTotals(quote)
  const accent = premiumUnlocked ? quote.accentColor || '#0f172a' : '#0f172a'

  const styles = StyleSheet.create({
    page: {
      padding: 36,
      fontSize: 11,
      fontFamily: 'Helvetica',
      color: '#0f172a',
      backgroundColor: '#ffffff',
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    header: {
      marginBottom: 20,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: '#e2e8f0',
    },
    logo: {
      width: 120,
      height: 48,
      objectFit: 'contain',
      marginBottom: 6,
    },
    brand: {
      fontSize: 20,
      color: accent,
      fontWeight: 700,
    },
    small: {
      fontSize: 10,
      color: '#475569',
    },
    h1: {
      fontSize: 18,
      fontWeight: 700,
      marginBottom: 6,
    },
    section: {
      marginTop: 18,
    },
    sectionTitle: {
      fontSize: 10,
      color: '#64748b',
      textTransform: 'uppercase',
      marginBottom: 8,
      fontWeight: 700,
    },
    text: {
      lineHeight: 1.4,
      color: '#0f172a',
    },
    itemRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 7,
      borderBottomWidth: 1,
      borderBottomColor: '#f1f5f9',
    },
    totalBox: {
      marginTop: 16,
      paddingTop: 12,
      borderTopWidth: 2,
      borderTopColor: accent,
    },
    totalLabel: {
      fontSize: 11,
      fontWeight: 700,
      color: '#0f172a',
    },
    totalValue: {
      fontSize: 16,
      fontWeight: 700,
      color: accent,
    },
    watermark: {
      position: 'absolute',
      bottom: 18,
      right: 36,
      fontSize: 9,
      color: '#94a3b8',
    },
  })

  const lineItems = [
    ['Flight / Shooting', totals.shooting],
    ['Editing / Post', totals.editing],
    ['Travel', totals.travel],
    ['Licensing / Usage', totals.licensing],
    ['Add-ons', totals.addons],
    ['Revision Buffer', totals.revisions],
  ].filter(([, value]) => Number(value) > 0)

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={[styles.row, styles.header]}>
          <View>
            {premiumUnlocked && quote.logoDataUrl ? (
              <Image src={quote.logoDataUrl} style={styles.logo} />
            ) : (
              <Text style={styles.brand}>{quote.businessName || 'QuoteRotor Media'}</Text>
            )}
            <Text style={styles.small}>Professional drone estimate</Text>
          </View>

          <View>
            <Text style={styles.small}>Estimate valid for {quote.validDays} days</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.h1}>{quote.projectTitle}</Text>
          <Text style={styles.text}>Prepared for: {quote.clientName || 'Client Name'}</Text>
          {!!quote.clientCompany && <Text style={styles.text}>{quote.clientCompany}</Text>}
          {!!quote.clientEmail && <Text style={styles.text}>{quote.clientEmail}</Text>}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Deliverables</Text>
          <Text style={styles.text}>{quote.deliverables}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Estimate Breakdown</Text>
          {lineItems.map(([label, value]) => (
            <View key={label} style={styles.itemRow}>
              <Text>{label}</Text>
              <Text>{formatCurrency(value)}</Text>
            </View>
          ))}
          <View style={[styles.row, styles.totalBox]}>
            <Text style={styles.totalLabel}>Estimated Total</Text>
            <Text style={styles.totalValue}>{formatCurrency(totals.subtotal)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Notes</Text>
          <Text style={styles.text}>{quote.notes}</Text>
        </View>

        {!premiumUnlocked && (
          <Text style={styles.watermark}>Generated by QuoteRotor</Text>
        )}
      </Page>
    </Document>
  )
}