import { useState } from 'react'

export default function PremiumModal({ isOpen, onClose }) {
  const [loading, setLoading] = useState(false)

  if (!isOpen) return null

  async function handleCheckout() {
    try {
      setLoading(true)

      const res = await fetch('/api/create-checkout-session', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({}),
      })

      const data = await res.json()

      if (!res.ok || !data.url) {
        throw new Error(data.error || 'Failed to create checkout session')
      }

      window.location.href = data.url
    } catch (error) {
      console.error(error)
      alert('Could not start Stripe checkout.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
      <div className="w-full max-w-lg rounded-3xl bg-white shadow-2xl">
        <div className="border-b border-slate-200 px-6 py-4">
          <div className="text-xl font-bold text-slate-900">Unlock QuoteRotor Premium</div>
          <div className="mt-1 text-sm text-slate-600">
            Remove the watermark and brand your quotes like a real business.
          </div>
        </div>

        <div className="px-6 py-5">
          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
            <div className="text-sm font-semibold text-slate-900">Included in premium</div>
            <ul className="mt-3 space-y-2 text-sm text-slate-700">
              <li>• Remove “Generated by QuoteRotor” watermark</li>
              <li>• Upload your business logo</li>
              <li>• Use custom accent colors</li>
              <li>• Create more polished client-facing exports</li>
            </ul>
          </div>

          <div className="mt-5 rounded-2xl bg-slate-900 p-5 text-white">
            <div className="text-sm uppercase tracking-wide text-slate-300">Launch price</div>
            <div className="mt-1 text-3xl font-bold">$49 one-time</div>
            <div className="mt-1 text-sm text-slate-300">Regular price $89</div>
          </div>
        </div>

        <div className="flex flex-col gap-3 border-t border-slate-200 px-6 py-4 sm:flex-row sm:justify-end">
          <button type="button" className="btn btn-secondary" onClick={onClose}>
            Maybe Later
          </button>

          <button
            type="button"
            className="btn btn-primary"
            onClick={handleCheckout}
            disabled={loading}
          >
            {loading ? 'Redirecting...' : 'Buy Premium'}
          </button>
        </div>
      </div>
    </div>
  )
}