import { useState } from 'react'

export default function PremiumModal({ isOpen, onClose }) {
  const [loading, setLoading] = useState(false)

  if (!isOpen) return null

  async function handleCheckout() {
    try {
      setLoading(true)

      const res = await fetch('/api/create-checkout-session', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({}),
      })

      const data = await res.json()

      if (!res.ok || !data.url) {
        throw new Error(data.error || 'Failed to create checkout session')
      }

      window.location.assign(data.url)
    } catch (error) {
      console.error('Stripe checkout error:', error)
      alert('Could not start Stripe checkout.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm">
      <div className="w-full max-w-2xl overflow-hidden rounded-[32px] border border-slate-200 bg-white shadow-2xl">
        <div className="border-b border-slate-200 bg-slate-50/80 px-6 py-5 md:px-8">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="text-3xl font-black tracking-tight text-slate-950">
                Unlock QuoteRotor Premium
              </div>
              <p className="mt-2 max-w-xl text-sm leading-6 text-slate-600">
                Remove the watermark, upload your branding, and send quotes that
                feel like a real paid service instead of a rough draft.
              </p>
            </div>

            <div className="feature-chip">One-time payment</div>
          </div>
        </div>

        <div className="grid gap-6 px-6 py-6 md:grid-cols-[1.2fr_0.8fr] md:px-8">
          <div className="grid gap-4">
            <div className="rounded-3xl border border-slate-200 bg-white p-5">
              <div className="text-sm font-bold uppercase tracking-[0.18em] text-slate-500">
                Included in premium
              </div>

              <div className="mt-4 grid gap-3 text-sm text-slate-700">
                <div className="rounded-2xl bg-slate-50 px-4 py-3">
                  Remove the “Generated by QuoteRotor” watermark
                </div>
                <div className="rounded-2xl bg-slate-50 px-4 py-3">
                  Upload your logo and brand your exports
                </div>
                <div className="rounded-2xl bg-slate-50 px-4 py-3">
                  Use custom accent colors
                </div>
                <div className="rounded-2xl bg-slate-50 px-4 py-3">
                  Restore premium later using your purchase email
                </div>
              </div>
            </div>

            <div className="rounded-3xl border border-blue-200 bg-blue-50 px-5 py-4 text-sm text-blue-900">
              Perfect for real estate drone shoots, roof inspections, construction progress updates, and fast client-ready estimates.
            </div>
          </div>

          <div className="rounded-[28px] bg-slate-950 p-6 text-white shadow-xl">
            <div className="text-xs font-bold uppercase tracking-[0.2em] text-slate-300">
              Launch price
            </div>
            <div className="mt-3 text-5xl font-black tracking-tight">$49</div>
            <div className="mt-2 text-sm text-slate-300">One-time payment</div>
            <div className="mt-1 text-sm text-slate-400">Regular price $89</div>

            <div className="divider-soft my-6" />

            <div className="text-sm leading-6 text-slate-300">
              Pay once with Stripe Checkout. Restore premium later with the same purchase email if you switch browsers or devices.
            </div>

            <button
              type="button"
              className="btn btn-primary mt-6 w-full"
              onClick={handleCheckout}
              disabled={loading}
            >
              {loading ? 'Redirecting...' : 'Buy Premium'}
            </button>

            <button
              type="button"
              className="btn btn-secondary mt-3 w-full border-white/20 bg-white/10 text-white hover:bg-white/15"
              onClick={onClose}
            >
              Maybe Later
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}